# App
spring.application.name=WorkNest
server.port=8080

# MongoDB
spring.data.mongodb.uri=your_mongodb_atlas_uri_here
spring.data.mongodb.database=worknest

# JWT
jwt.secret=your_jwt_secret_key_here
jwt.expiration=86400000